const latex = String.raw

export const STUDYME_SUBJECTS = [
  {
    id: 'financial-management',
    title: 'Financial Management',
    description: 'Exam-focused lesson roadmap for quick revision and practice planning.',
    pdfPath: '/pdfs/fm.pdf',
    lessons: [
      {
        id: 'fm-01',
        lessonNumber: 1,
        title: 'Introduction to Financial Management',
        covers: 'Financial goals, agency issues, asset types, financial systems, and sustainability.',
        pageRange: { start: 17, end: 106 },
        tags: ['theory-heavy'],
        formulas: [],
        topics: [
          {
            id: 'fm-01-t1',
            title: 'Form of business organization',
            summary: 'Introduces what financial management covers and why wealth maximization is preferred.',
            subtopics: [
              'sole proprietorship,partnership,OPC,corporation',
              'Profit maximization vs wealth maximization',
              'Agency relationship; Agency problem; Agency cost',
              'Real Asset & Financial Asset',
            ],
            pageRange: { start: 18, end: 78 },
            hasNumericals: false,
            hasExamples: true,
          },
          {
            id: 'fm-01-t2',
            title: 'Introduction to the Indian financial system',
            summary: 'overview of indian financial system.',
            subtopics: [
              'features',
              'Functions(finance market:money market,capital market)',
              'Overview of SDGs',
            ],
            pageRange: { start: 79, end: 106 },
            hasNumericals: false,
            hasExamples: true,
          },
        ],
      },
      {
        id: 'fm-02',
        lessonNumber: 2,
        title: 'Time Value of Money',
        covers: 'How cash flows change over time using compounding, discounting, and annuity concepts.',
        pageRange: { start: 107, end: 166 },
        tags: ['formula-heavy', 'practice-heavy'],
        formulas: [
          {
            name: 'Future Value',
            formula: 'FV = PV(1 + r)^n',
            latex: 'FV = PV(1 + r)^n',
            notation: {
              FV: 'Future Value of money',
              PV: 'Present Value (today\'s amount)',
              r: 'Rate of return per period',
              n: 'Number of compounding periods',
            },
          },
          {
            name: 'Present Value',
            formula: 'PV = FV / (1 + r)^n',
            latex: 'PV = \\frac{FV}{(1 + r)^n}',
            notation: {
              PV: 'Present Value (today\'s amount)',
              FV: 'Future Value',
              r: 'Discount rate per period',
              n: 'Number of periods',
            },
          },
          {
            name: 'Future Value of Annuity',
            formula: 'FVA = A[((1 + r)^n - 1) / r]',
            latex: 'FVA = A\\left(\\frac{(1 + r)^n - 1}{r}\\right)',
            notation: {
              FVA: 'Future Value of Annuity',
              A: 'Equal payment made each period',
              r: 'Rate per period',
              n: 'Number of payments/periods',
            },
          },
          {
            name: 'Present Value of Annuity',
            formula: 'PVA = A[(1 - (1 + r)^-n) / r]',
            latex: 'PVA = A\\left(\\frac{1 - (1 + r)^{-n}}{r}\\right)',
            notation: {
              PVA: 'Present Value of Annuity',
              A: 'Equal payment each period',
              r: 'Discount rate per period',
              n: 'Total number of periods',
            },
          },
          {
            name: 'EMI',
            formula: 'EMI= P * r * (1 + r)^n / (1+r)^n -1 ',
            latex: 'EMI = \\frac{P \\cdot r \\cdot (1 + r)^n}{(1 + r)^n - 1}',
            notation: {
              EMI: 'Equal Monthly Installment',
              P: 'Principal loan amount',
              r: 'Monthly interest rate',
              n: 'Total number of installments',
            },
          },
        ],
        numericals: [
          {
            id: 'fm-02-se-01',
            topicId: 'fm-02-t1',
            type: 'solved-example',
            title: 'Future Value of Single Amount',
            questionType: 'Direct Value',
            difficulty: 'easy',
            question: 'How much will Rs 75,000 grow to in 5 years at 9% annual compounding?',
            asksFor: 'Future value at the end of year 5.',
            identifiedValues: ['PV = 75,000', 'r = 9% = 0.09', 'n = 5 years'],
            formulaRef: 'Future Value',
            formulaReason: 'A single present amount is invested for multiple years, so compounding on PV is required.',
            substitution: 'FV = 75,000 x (1 + 0.09)^5 = 75,000 x 1.5386',
            steps: [
              'Write given values and convert 9% into 0.09.',
              'Choose FV = PV(1 + r)^n because this is a direct future accumulation problem.',
              'Compute growth factor: (1.09)^5 = 1.5386.',
              'Multiply principal and growth factor: 75,000 x 1.5386 = 115,395.',
            ],
            finalAnswer: 'Future Value = Rs 115,395 (approx.)',
            examTip: 'If compounding is annual, keep r annual and n in years. Do not mix monthly n with annual r.',
          },
          {
            id: 'fm-02-se-02',
            topicId: 'fm-02-t1',
            type: 'solved-example',
            title: 'Present Value / Discounting Factor',
            questionType: 'Direct Value',
            difficulty: 'easy',
            question: 'A company will receive Rs 180,000 after 4 years. Find its present value at a discount rate of 10%.',
            asksFor: 'Current worth of the future cash inflow.',
            identifiedValues: ['FV = 180,000', 'r = 10% = 0.10', 'n = 4 years'],
            formulaRef: 'Present Value',
            formulaReason: 'The cash flow is given in future terms, so it must be discounted to today.',
            substitution: 'PV = 180,000 / (1 + 0.10)^4 = 180,000 / 1.4641',
            steps: [
              'Mark the cash flow timing: amount is received after 4 years.',
              'Use PV = FV / (1 + r)^n for discounting.',
              'Find discount factor denominator: (1.10)^4 = 1.4641.',
              'Divide future amount by factor: 180,000 / 1.4641 = 122,943.',
            ],
            finalAnswer: 'Present Value = Rs 122,943 (approx.)',
            examTip: 'Discounting reduces value as time increases; compounding increases value.',
          },
          {
            id: 'fm-02-se-03',
            topicId: 'fm-02-t1',
            type: 'solved-example',
            title: 'Future Value of Ordinary Annuity',
            questionType: 'Annuity',
            difficulty: 'medium',
            question: 'You deposit Rs 12,000 at the end of each year for 6 years at 8%. Find the accumulated amount.',
            asksFor: 'Future value of equal end-of-year deposits.',
            identifiedValues: ['A = 12,000', 'r = 8% = 0.08', 'n = 6'],
            formulaRef: 'Future Value of Annuity',
            formulaReason: 'Equal periodic end-of-year deposits form an ordinary annuity.',
            substitution: 'FVA = 12,000 x [((1 + 0.08)^6 - 1) / 0.08] = 12,000 x 7.3359',
            steps: [
              'Identify it as ordinary annuity because payment is at year-end.',
              'Use FVA = A[((1 + r)^n - 1) / r].',
              'Compute annuity factor: ((1.08)^6 - 1) / 0.08 = 7.3359.',
              'Multiply by annual payment: 12,000 x 7.3359 = 88,031.',
            ],
            finalAnswer: 'Future Value of Annuity = Rs 88,031 (approx.)',
            examTip: 'If the question says beginning-of-year payments, convert using annuity-due adjustment.',
          },
          {
            id: 'fm-02-se-04',
            topicId: 'fm-02-t1',
            type: 'solved-example',
            title: 'Present Value of Annuity',
            questionType: 'Annuity',
            difficulty: 'medium',
            question: 'Find the present value of receiving Rs 18,000 each year for 5 years at 11%.',
            asksFor: 'Current value of an ordinary annuity stream.',
            identifiedValues: ['A = 18,000', 'r = 11% = 0.11', 'n = 5'],
            formulaRef: 'Present Value of Annuity',
            formulaReason: 'The question gives equal future receipts and asks their value today.',
            substitution: 'PVA = 18,000 x [(1 - (1 + 0.11)^-5) / 0.11] = 18,000 x 3.6959',
            steps: [
              'Confirm this is ordinary annuity (end-of-year receipts).',
              'Use PVA = A[(1 - (1 + r)^-n) / r].',
              'Compute annuity present value factor: 3.6959.',
              'Multiply by annual amount: 18,000 x 3.6959 = 66,526.',
            ],
            finalAnswer: 'Present Value of Annuity = Rs 66,526 (approx.)',
            examTip: 'For annuity-due, multiply ordinary annuity value by (1 + r).',
          },
          {
            id: 'fm-02-pq-01',
            topicId: 'fm-02-t1',
            type: 'practice-question',
            title: 'Reverse Style: Find Required Interest Rate',
            questionType: 'Rate Finding',
            difficulty: 'exam-level',
            question: 'An investment of Rs 90,000 grows to Rs 131,769 in 4 years. Find the annual compound rate.',
            asksFor: 'Annual compound rate r.',
            identifiedValues: ['PV = 90,000', 'FV = 131,769', 'n = 4'],
            formulaRef: 'Future Value',
            formulaReason: 'Given PV and FV for a single amount, use FV = PV(1 + r)^n and solve for r.',
            substitution: '(1 + r)^4 = 131,769 / 90,000 = 1.4641, so 1 + r = (1.4641)^(1/4)',
            steps: [
              'Rearrange formula: (1 + r)^n = FV / PV.',
              'Substitute values: (1 + r)^4 = 1.4641.',
              'Take fourth root: 1 + r = 1.10.',
              'Hence r = 0.10 = 10% p.a.',
            ],
            hint: 'First isolate (1 + r)^n, then use root operation.',
            finalAnswer: 'Required annual compound rate = 10%',
            examTip: 'Reverse questions usually test algebraic rearrangement accuracy more than arithmetic.',
          },
          {
            id: 'fm-02-pq-02',
            topicId: 'fm-02-t1',
            type: 'practice-question',
            title: 'Reverse Style: Find Required Time',
            questionType: 'Time Finding',
            difficulty: 'medium',
            question: 'How many years will Rs 60,000 take to become Rs 95,244 at 8% annual compounding?',
            asksFor: 'Number of years n.',
            identifiedValues: ['PV = 60,000', 'FV = 95,244', 'r = 8% = 0.08'],
            formulaRef: 'Future Value',
            formulaReason: 'Unknown variable is n in single cash-flow compounding.',
            substitution: '(1.08)^n = 95,244 / 60,000 = 1.5874',
            steps: [
              'Rewrite as (1 + r)^n = FV / PV.',
              'Compute RHS ratio = 1.5874.',
              'At 8%, (1.08)^6 = 1.5869 which is closest to required ratio.',
              'Therefore n is approximately 6 years.',
            ],
            hint: 'Use log method or trial with compounding table values.',
            finalAnswer: 'Required time = approximately 6 years',
          },
          {
            id: 'fm-02-mn-01',
            topicId: 'fm-02-t1',
            type: 'mistake-note',
            title: 'Percentage to Decimal Error',
            content: 'Students often put r = 9 instead of r = 0.09. Always convert percentage into decimal before substitution.',
            questionType: 'Direct Value',
          },
          {
            id: 'fm-02-mn-02',
            topicId: 'fm-02-t1',
            type: 'mistake-note',
            title: 'PV vs FV Formula Confusion',
            content: 'If amount is given in future and asked today, use discounting. If amount is given today and asked in future, use compounding.',
            questionType: 'Direct Value',
          },
          {
            id: 'fm-02-se-05',
            topicId: 'fm-02-t2',
            type: 'solved-example',
            title: 'Present Value of Perpetuity',
            questionType: 'Perpetuity',
            difficulty: 'medium',
            question: 'An investor expects Rs 9,000 every year forever. If required return is 12%, find present value.',
            asksFor: 'Current value of perpetual annual cash flow.',
            identifiedValues: ['A = 9,000', 'r = 12% = 0.12'],
            formulaRef: 'Present Value of Perpetuity',
            formulaUsedFallback: 'PV_{perpetuity} = A / r',
            formulaReason: 'Cash flow continues indefinitely with constant annual amount, so perpetuity formula is used.',
            substitution: 'PV = 9,000 / 0.12',
            steps: [
              'Recognize that n is infinite in perpetuity.',
              'Use PV of perpetuity = A / r.',
              'Substitute values: 9,000 / 0.12.',
              'Compute: 75,000.',
            ],
            finalAnswer: 'Present Value of Perpetuity = Rs 75,000',
            examTip: 'If growth in perpetuity is provided, use growing perpetuity formula instead of A/r.',
          },
          {
            id: 'fm-02-pq-03',
            topicId: 'fm-02-t2',
            type: 'practice-question',
            title: 'Ordinary Annuity Present Value Practice',
            questionType: 'Annuity',
            difficulty: 'medium',
            question: 'You will receive Rs 15,000 at the end of each year for 7 years. Discount rate is 10%. Find present value.',
            asksFor: 'Present value of the annuity stream.',
            identifiedValues: ['A = 15,000', 'r = 10% = 0.10', 'n = 7'],
            formulaRef: 'Present Value of Annuity',
            formulaReason: 'Equal cash inflows at the end of each year represent ordinary annuity.',
            substitution: 'PVA = 15,000 x [(1 - (1.10)^-7) / 0.10] = 15,000 x 4.8684',
            steps: [
              'Use PVA formula for end-of-year equal cash flows.',
              'Calculate factor: (1 - (1.10)^-7) / 0.10 = 4.8684.',
              'Multiply factor by annuity amount: 15,000 x 4.8684 = 73,026.',
            ],
            hint: 'Do not use FV annuity formula when the question asks value today.',
            finalAnswer: 'Present Value = Rs 73,026 (approx.)',
          },
          {
            id: 'fm-02-pq-04',
            topicId: 'fm-02-t2',
            type: 'practice-question',
            title: 'Annuity Due Conversion',
            questionType: 'Annuity',
            difficulty: 'exam-level',
            question: 'Rent of Rs 20,000 is paid at the beginning of each year for 5 years. Discount rate is 9%. Find present value.',
            asksFor: 'Present value of annuity-due payments.',
            identifiedValues: ['A = 20,000', 'r = 9% = 0.09', 'n = 5'],
            formulaRef: 'Present Value of Annuity',
            formulaReason: 'Beginning-of-period payment means annuity due. Start from ordinary PVA and adjust by (1 + r).',
            substitution: 'PVAD = [20,000 x ((1 - (1.09)^-5) / 0.09)] x 1.09 = (20,000 x 3.8897) x 1.09',
            steps: [
              'Compute ordinary annuity PV factor first: 3.8897.',
              'Ordinary PV = 20,000 x 3.8897 = 77,794.',
              'Convert to annuity due: 77,794 x 1.09 = 84,795.',
            ],
            hint: 'Annuity due value is always higher than ordinary annuity value when r > 0.',
            finalAnswer: 'Present Value (annuity due) = Rs 84,795 (approx.)',
          },
          {
            id: 'fm-02-mn-03',
            topicId: 'fm-02-t2',
            type: 'mistake-note',
            title: 'Ordinary Annuity vs Annuity Due Mix-Up',
            content: 'If cash flow happens at beginning, multiply ordinary annuity value by (1 + r). Skipping this gives lower answer.',
            questionType: 'Annuity',
          },
          {
            id: 'fm-02-mn-04',
            topicId: 'fm-02-t2',
            type: 'mistake-note',
            title: 'Wrong Formula for Perpetuity',
            content: 'Students often plug perpetuity into annuity formula with finite n. For perpetual equal cash flow, use A/r.',
            questionType: 'Perpetuity',
          },
          {
            id: 'fm-02-se-06',
            topicId: 'fm-02-t3',
            type: 'solved-example',
            title: 'EMI and First-Year Amortization Snapshot',
            questionType: 'Loan / EMI',
            difficulty: 'exam-level',
            question: 'A loan of Rs 120,000 is repaid in 12 equal monthly installments at 12% p.a. Prepare EMI and first 4 months of amortization schedule.',
            asksFor: 'EMI and month-wise split of interest and principal.',
            identifiedValues: ['P = 120,000', 'Annual rate = 12%', 'Monthly rate r = 1% = 0.01', 'n = 12 months'],
            formulaRef: 'EMI',
            formulaReason: 'Loan repayment with equal monthly installments is solved using EMI formula, then split each month into interest and principal.',
            substitution: 'EMI = [120,000 x 0.01 x (1.01)^12] / [(1.01)^12 - 1] = 10,661.85',
            steps: [
              'Compute EMI using monthly rate and total months.',
              'Month interest = Opening principal x 1%.',
              'Principal repaid = EMI - Interest.',
              'Closing principal = Opening principal - Principal repaid.',
              'Repeat month by month for schedule.',
            ],
            finalAnswer: 'EMI = Rs 10,661.85 (approx.)',
            examTip: 'In amortization tables, rounding each month slightly changes last installment; mention rounding in exam notes.',
            amortizationTable: {
              columns: ['Month', 'Opening Principal', 'Interest (1%)', 'EMI', 'Principal Repaid', 'Closing Principal'],
              rows: [
                ['1', '120,000.00', '1,200.00', '10,661.85', '9,461.85', '110,538.15'],
                ['2', '110,538.15', '1,105.38', '10,661.85', '9,556.47', '100,981.68'],
                ['3', '100,981.68', '1,009.82', '10,661.85', '9,652.03', '91,329.65'],
                ['4', '91,329.65', '913.30', '10,661.85', '9,748.55', '81,581.10'],
              ],
            },
          },
          {
            id: 'fm-02-pq-05',
            topicId: 'fm-02-t3',
            type: 'practice-question',
            title: 'Loan Outstanding After 6 Installments',
            questionType: 'Loan / EMI',
            difficulty: 'exam-level',
            question: 'Loan amount is Rs 250,000 at 12% p.a. for 24 monthly EMIs. Find outstanding principal after 6 installments.',
            asksFor: 'Balance principal after month 6.',
            identifiedValues: ['P = 250,000', 'r = 12%/12 = 1% per month', 'n = 24'],
            formulaRef: 'EMI',
            formulaReason: 'Need EMI first, then reduce principal installment by installment to get outstanding balance.',
            substitution: 'EMI = [250,000 x 0.01 x (1.01)^24] / [(1.01)^24 - 1] = 11,768.58',
            steps: [
              'Compute EMI using monthly rate and months.',
              'For each month: Interest = Opening x 1%, Principal repaid = EMI - Interest.',
              'Update opening principal for next month.',
              'After 6th month, closing principal is the outstanding balance.',
            ],
            hint: 'Use a schedule table; direct guessing usually causes arithmetic errors.',
            finalAnswer: 'Outstanding principal after 6 EMIs = Rs 192,092 (approx.)',
            amortizationTable: {
              columns: ['Month', 'Opening Principal', 'Interest (1%)', 'EMI', 'Principal Repaid', 'Closing Principal'],
              rows: [
                ['1', '250,000.00', '2,500.00', '11,768.58', '9,268.58', '240,731.42'],
                ['2', '240,731.42', '2,407.31', '11,768.58', '9,361.27', '231,370.15'],
                ['3', '231,370.15', '2,313.70', '11,768.58', '9,454.88', '221,915.27'],
                ['4', '221,915.27', '2,219.15', '11,768.58', '9,549.43', '212,365.84'],
                ['5', '212,365.84', '2,123.66', '11,768.58', '9,644.92', '202,720.92'],
                ['6', '202,720.92', '2,027.21', '11,768.58', '9,741.37', '192,979.55'],
              ],
            },
          },
          {
            id: 'fm-02-mn-05',
            topicId: 'fm-02-t3',
            type: 'mistake-note',
            title: 'Annual Rate with Monthly n Mismatch',
            content: 'When n is in months, rate must also be monthly. Using annual rate with monthly n inflates interest wrongly.',
            questionType: 'Loan / EMI',
          },
          {
            id: 'fm-02-mn-06',
            topicId: 'fm-02-t3',
            type: 'mistake-note',
            title: 'Interest Computed on Original Principal Every Month',
            content: 'In amortization schedules interest is on opening balance of each month, not on original loan every time.',
            questionType: 'Loan / EMI',
          },
        ],
        topics: [
          {
            id: 'fm-02-t1',
            title: 'Compounding and Discounting Basics',
            summary: 'Builds intuition for present value and future value under a given interest rate.',
            subtopics: [
              'Future value of single cash flow',
              'Present value of Single cash flow ',
              'simple and compound interest',
              'doubling period (rule 72)',
              'present and future value of uneven cash flow series',
              'Discount factor interpretation',
            ],
            pageRange: { start: 115, end: 147 },
            hasNumericals: true,
            hasExamples: true,
          },
          {
            id: 'fm-02-t2',
            title: 'Annuities and Perpetuities',
            summary: 'Explains equal periodic cash flows and standard annuity variants.',
            subtopics: [
              'Ordinary annuity vs annuity due',
              'Future and present value of annuities',
              'Perpetuity fundamentals',
            ],
            pageRange: { start: 148, end: 177 },
            hasNumericals: true,
            hasExamples: true,
          },
          {
            id: 'fm-02-t3',
            title: 'Loan Amortization schedule',
            summary: 'A loan schedule shows how your loan is paid off step by step with each payment.',
            subtopics: [
              'Definition & key characteristics',
              'how is the instalment (A) determined?',
              'preparing loan amortization schedule (numericlas)',
            ],
            pageRange: { start: 178, end: 189 },
            hasNumericals: true,
            hasExamples: true,
          },
        ],
      },
      {
        id: 'fm-03',
        lessonNumber: 3,
        title: 'Risk and Return',
        covers: 'Relationship between expected return and risk using probability, variability, and portfolio views.',
        pageRange: { start: 212, end: 344 },
        tags: ['theory-heavy', 'practice-heavy'],
        formulaSections: [
          {
            title: 'Expected Return',
            description: 'Measures average return using different approaches.',
            formulas: [
              {
                name: 'Expected Return',
                formula: 'E(R) = Sigma[p_i * R_i]',
                latex: latex`E(R) = \sum_{i=1}^{n} p_i R_i`,
                notation: {
                  'E(R)': 'Expected return',
                  p_i: 'Probability of outcome i',
                  R_i: 'Return in scenario i',
                  i: 'Index of each possible outcome',
                  n: 'Total number of outcomes',
                },
              },
              {
                name: 'Arithmetic / Average Annual Return',
                formula: 'R(bar) = Sigma R_i / n',
                latex: latex`\bar{R} = \frac{\sum_{i=1}^{n} R_i}{n}`,
                notation: {
                  [latex`\bar{R}`]: 'Arithmetic average return',
                  R_i: 'Return in year/period i',
                  n: 'Total number of years/periods',
                  i: 'Period index from 1 to n',
                },
              },
              {
                name: 'Geometric Return',
                formula: 'R_g = [(1+R_1)(1+R_2)...(1+R_n)]^(1/n)-1',
                latex: latex`R_g = \left[(1 + R_1)(1 + R_2)\cdots(1 + R_n)\right]^{\frac{1}{n}} - 1`,
                notation: {
                  R_g: 'Geometric (compound average) return',
                  R_i: 'Return in period i',
                  [latex`\cdots`]: 'Multiply all terms from (1 + R_1) to (1 + R_n)',
                  n: 'Total number of periods',
                },
              },
            ],
          },
          {
            title: 'Measurement of Risk',
            description: 'Measures variability and uncertainty in returns.',
            formulas: [
              {
                name: 'Historical Risk (Variance)',
                formula: 'σ² = Σ(R_t - R̄)² / (n - 1)',
                latex: latex`\sigma^2 = \frac{\sum_{t=1}^{n}(R_t - \bar{R})^2}{n - 1}`,
                notation: {
                  [latex`\sigma^2`]: 'Variance (historical risk)',
                  R_t: 'Return in time period t',
                  [latex`\bar{R}`]: 'Average return',
                  n: 'Number of years',
                },
              },
              {
                name: 'Expected Risk (Variance)',
                formula: 'σ² = Σ pᵢ (Rᵢ - E(R))²',
                latex: latex`\sigma^2 = \sum_{i=1}^{n} p_i (R_i - E(R))^2`,
                notation: {
                  [latex`\sigma^2`]: 'Variance (expected risk)',
                  p_i: 'Probability of outcome i',
                  R_i: 'Return in scenario i',
                  'E(R)': 'Expected return',
                  n: 'Number of outcomes',
                },
              },
              {
                name: 'Standard Deviation',
                formula: 'sigma = square root of variance',
                latex: latex`\sigma = \sqrt{\sigma^2}`,
                notation: {
                  [latex`\sigma`]: 'Standard deviation (total risk)',
                  [latex`\sigma^2`]: 'Variance (average squared deviation from mean return)',
                },
              },
              {
                name: 'Coefficient of Variation',
                formula: 'CV = sigma / E(R)',
                latex: latex`CV = \frac{\sigma}{E(R)}`,
                notation: {
                  CV: 'Coefficient of variation',
                  [latex`\sigma`]: 'Standard deviation',
                  'E(R)': 'Expected return',
                },
              },
            ],
          },
          {
            title: 'Systematic Risk (Market Risk)',
            formulas: [
              {
                name: 'Beta (β)',
                formula: 'β = Cov(R_i, R_m) / σ_m²',
                latex: latex`\beta = \frac{\mathrm{Cov}(R_i, R_m)}{\sigma_m^2}`,
                notation: {
                  [latex`\beta`]: 'Systematic risk coefficient',
                  'numerator': 'covariance between stock and market',
                  'denominator': 'variance of the market',
                },
              },
              {
                name: 'Covariance (Numerator of Beta)',
                formula: 'Cov(R_j, R_m) = Σ[(R_jt − R̄_j)(R_mt − R̄_m)] / (n − 1)',
                latex: latex`\mathrm{Cov}(R_j, R_m) = \frac{\sum_{t=1}^{n}(R_{jt} - \bar{R}_j)(R_{mt} - \bar{R}_m)}{n - 1}`,
                notation: {
                  [latex`\mathrm{Cov}(R_j, R_m)`]: 'Covariance between security j and market',
                  R_jt: 'Return of security j at time t',
                  R_mt: 'Return of market at time t',
                  [latex`\bar{R}_j`]: 'Average return of security j',
                  [latex`\bar{R}_m`]: 'Average return of market',
                  n: 'Number of observations',
                },
              },
              {
                name: 'Variance of Market (Denominator of Beta)',
                formula: 'σ_m² = Σ(R_mt − R̄_m)² / (n − 1)',
                latex: latex`\sigma_m^2 = \frac{\sum_{t=1}^{n}(R_{mt} - \bar{R}_m)^2}{n - 1}`,
                notation: {
                  [latex`\sigma_m^2`]: 'Variance of market returns',
                  R_mt: 'Market return at time t',
                  [latex`\bar{R}_m`]: 'Average market return',
                  n: 'Number of observations',
                },
              },
            ],
          }
        ],
        topics: [
          {
            id: 'fm-03-t1',
            title: 'Foundations of Risk and Return',
            summary: 'Introduces expected return and uncertainty in investment outcomes.',
            subtopics: [
              'Meaning of risk and return',
              'expected return (numerical)',
              'arithmetic vs geometric return(numerical)',
            ],
            pageRange: { start: 212, end: 246 },
            hasNumericals: true,
            hasExamples: true,
          },
          {
            id: 'fm-03-t2',
            title: 'Market Return',
            summary: 'Covers variance, standard deviation, and coefficient of variation comparisons.',
            subtopics: [
              'Meaning of index, market index, and market return',
              'Historical risk: explain variance and standard deviation using past return data',
              'Expected risk: explain variance and standard deviation using probability distribution and expected return',
              'For historical risk, include one full numerical example in table format and solve variance and standard deviation step by step',
              'For expected risk, include one full numerical example in table format with probabilities, expected return, variance, and standard deviation, and solve step by step',
              'Explain how to read and prepare the required calculation tables for both historical risk and expected risk',
              'Coefficient of variation: meaning, formula, interpretation, and comparative risk decision-making',
              'Interpreting dispersion and risk comparison in exam-style problems'
            ],
            pageRange: { start: 247, end: 293},
            hasNumericals: true,
            hasExamples: true,
          },
          {
            id: 'fm-03-t3',
            title: 'Different categories of Investors',
            summary: 'Explains diversification and introduces market-linked risk interpretation.',
            subtopics: [
              'Systematic and unsystematic risk',
              'Portfolio diversification logic(risk averse,risk neutral,risk loving)',
              'Beta',
            ],
            pageRange: { start: 293, end: 345 },
            hasNumericals: true,
            hasExamples: true,
          },
        ],
      },
      {
        id: 'fm-04',
        lessonNumber: 4,
        title: 'Bond and Equity Valuation',
        covers: 'Valuation of bonds and shares using present value concepts, yield measures, and dividend models.',
        pageRange: { start: 345, end: 420 },
        tags: ['formula-heavy', 'practice-heavy'],

        formulaSections: [
          {
            title: 'Bond Valuation',
            description: 'Determines the intrinsic value of a bond using discounted cash flows.',
            formulas: [
              {
                name: 'Bond Value',
                formula: 'V = Σ [C / (1+r)^t] + FV / (1+r)^n',
                latex: 'V = \\sum_{t=1}^{n} \\frac{C}{(1 + r)^t} + \\frac{FV}{(1 + r)^n}',
                notation: {
                  V: 'Value of bond',
                  C: 'Annual coupon payment',
                  r: 'Required rate of return (YTM)',
                  FV: 'Face value of bond',
                  t: 'Time period',
                  n: 'Number of years to maturity',
                },
              },
              {
                name: 'Bond Value (Shortcut / PV Form)',
                formula: 'V = C × PVIFA(r,n) + FV × PVIF(r,n)',
                latex: 'V = C \\cdot PVIFA(r,n) + FV \\cdot PVIF(r,n)',
                notation: {
                  V: 'Value of bond',
                  C: 'Annual coupon payment',
                  r: 'Required rate of return (YTM)',
                  n: 'Number of years to maturity',
                  FV: 'Face value of bond',
                  PVIFA: 'Present Value Interest Factor of Annuity (for r and n)',
                  PVIF: 'Present Value Interest Factor (for r and n)'
                },
              },
              {
                name: 'Yield to Maturity (YTM)',
                formula: 'Approx YTM = [C + (FV - P)/n] / [(FV + P)/2]',
                latex: '\\text{YTM} \\approx \\frac{C + \\frac{FV - P}{n}}{\\frac{FV + P}{2}}',
                notation: {
                  YTM: 'Yield to maturity',
                  C: 'Coupon payment',
                  FV: 'Face value',
                  P: 'Current market price',
                  n: 'Years to maturity',
                },
              },
            ],
          },
          {
            title: 'Equity Valuation',
            description: 'Determines share value using dividend-based valuation models.',
            formulas: [
              {
                name: 'Dividend Discount Model (DDM)',
                formula: 'P0 = D1 / (r - g)',
                latex: 'P_0 = \\frac{D_1}{r - g}',
                notation: {
                  P_0: 'Current share price',
                  D_1: 'Expected dividend next year',
                  r: 'Required rate of return',
                  g: 'Growth rate of dividends',
                },
              },
              {
                name: 'Zero Growth Model',
                formula: 'P0 = D / r',
                latex: 'P_0 = \\frac{D}{r}',
                notation: {
                  P_0: 'Share price',
                  D: 'Constant dividend',
                  r: 'Required rate of return',
                },
              },
              {
                name: 'Single Period Valuation Model',
                formula: 'P₀ = (D₁ + P₁) / (1 + k)',
                latex: 'P_0 = \\frac{D_1 + P_1}{1 + k}',
                notation: {
                  'P_0': 'Current price of the share',
                  'D_1': 'Dividend expected at the end of the period',
                  'P_1': 'Expected selling price at the end of the period',
                  'k': 'Required rate of return (cost of equity)',
                },
              },
            ],
          },
        ],

        topics: [
          {
            id: 'fm-04-t1',
            title: 'Bond Valuation Concepts',
            summary: 'Explains how bond prices are determined and how yield is interpreted.',
            subtopics: [
              'numericals on value of bond, bond with semi-annual interest',
              'Bond pricing using present value (numerical)',
              'Relationship between bond price and interest rate',
              'Premium, discount, and par bonds',
              'Yield to maturity (YTM) (numerical)',
              'Current yield vs YTM',
            ],
            pageRange: { start: 345, end: 390 },
            hasNumericals: true,
            hasExamples: true,
          },
          {
            id: 'fm-04-t2',
            title: 'Equity Valuation Models',
            summary: 'Covers valuation of shares using dividend-based approaches.',
            subtopics: [
              'Meaning of equity valuation',
              'Dividend discount model (DDM) (numerical)',
              'Zero growth model (numerical)',
              'single period valuation model',
            ],
            pageRange: { start: 393, end: 410 },
            hasNumericals: true,
            hasExamples: true,
          },
        ],
      },
      {
        id: 'fm-05',
        lessonNumber: 5,
        title: 'Cost of Capital',
        covers: 'Determination of cost of different sources of finance and overall weighted average cost of capital for decision making.',
        pageRange: { start: 421, end: 500 },
        tags: ['formula-heavy', 'practice-heavy'],

        formulaSections: [
          {
            title: 'Cost of Individual Sources',
            description: 'Calculates cost of debt, preference shares, and equity.',
            formulas: [
              {
                name: 'Cost of Debt',
                formula: 'r_D = [I + (F - P₀) / n] / [0.6P₀ + 0.4F]',
                latex: 'r_D = \\frac{I + \\frac{F - P_0}{n}}{0.6P_0 + 0.4F}',
                notation: {
                  "r_D": "Cost of debt",
                  "I": "Annual interest payment",
                  "F": "Face (redemption) value of debt",
                  "P_0": "Net proceeds / issue price of debt",
                  "n": "Number of years to maturity",
                },
              },
              {
                name: 'Cost of Preference Shares',
                formula: 'K_p = [D + (F - P₀) / n] / [0.6P₀ + 0.4F]',
                latex: 'K_p = \\frac{D + \\frac{F - P_0}{n}}{0.6P_0 + 0.4F}',
                notation: {
                  "K_p": "Cost of preference capital",
                  "D": "Annual preference dividend",
                  "F": "Face (redemption) value",
                  "P_0": "Net proceeds / issue price",
                  "n": "Number of years to maturity",
                },
              },
              {
                name: 'Cost of Equity (Dividend Growth Model)',
                formula: 'Ke = (D1 / P0) + g',
                latex: 'K_e = \\frac{D_1}{P_0} + g',
                notation: {
                  K_e: 'Cost of equity',
                  D_1: 'Expected dividend next year',
                  P_0: 'Current market price',
                  g: 'Growth rate',
                },
              },
            ],
          },
          {
            title: 'Weighted Average Cost of Capital',
            description: 'Combines all sources of finance to determine overall cost.',
            formulas: [
              {
                name: 'WACC',
                formula: 'WACC = W_E × R_E + W_P × R_P + W_D × R_D (1 - t_c)',
                latex: 'WACC = W_E R_E + W_P R_P + W_D R_D (1 - t_c)',
                notation: {
                  "WACC": "Weighted average cost of capital",
                  "W_E": "Weight of equity",
                  "R_E": "Cost of equity",
                  "W_P": "Weight of preference shares",
                  "R_P": "Cost of preference shares",
                  "W_D": "Weight of debt",
                  "R_D": "Cost of debt",
                  "t_c": "Corporate tax rate",
                },
              },
            ],
          },
        ],

        topics: [
          {
            id: 'fm-05-t1',
            title: 'Introduction to Cost of Capital',
            summary: 'Explains the concept and importance of cost of capital in financial decisions.',
            subtopics: [
              'Meaning of cost of capital',
              'Explicit vs implicit cost',
              'Importance in investment and financing decisions',
              'Opportunity cost concept',
            ],
            pageRange: { start: 415, end: 427 },
            hasNumericals: false,
            hasExamples: true,
          },
          {
            id: 'fm-05-t2',
            title: 'Cost of Debt and Preference Capital',
            summary: 'Covers calculation of cost for fixed-income sources of finance.',
            subtopics: [
              'Cost of debt before and after tax (numerical)',
              'Irredeemable debt vs redeemable debt (numerical)',
              'Tax shield on debt',
              'Cost of preference shares (numerical)',
              'Redeemable vs irredeemable preference shares',
            ],
            pageRange: { start: 428, end: 448 },
            hasNumericals: true,
            hasExamples: true,
          },
          {
            id: 'fm-05-t3',
            title: 'Cost of Equity and Retained Earnings',
            summary: 'Explains cost of ownership capital using different approaches.',
            subtopics: [
              'Cost of equity using dividend growth model (numerical)',
              'Cost of equity using earnings approach',
              'Cost of retained earnings (numerical)',
              'Comparison between equity and retained earnings cost',
            ],
            pageRange: { start: 449, end: 480 },
            hasNumericals: true,
            hasExamples: true,
          },
          {
            id: 'fm-05-t4',
            title: 'Weighted Average Cost of Capital (WACC)',
            summary: 'Combines costs of all sources to determine overall cost of capital.',
            subtopics: [
              'Meaning and purpose of WACC',
              'Calculation of WACC using book value weights (numerical)',
              'Calculation of WACC using market value weights (numerical)',
              'Marginal cost of capital',
              'Use of WACC in investment decisions',
            ],
            pageRange: { start: 486, end: 500 },
            hasNumericals: true,
            hasExamples: true,
          },
        ],
      },
      {
        id: 'fm-06',
        lessonNumber: 6,
        title: 'Capital Structure and Firm Value',
        covers: 'Explains how debt-equity mix affects firm value, cost of capital, shareholder wealth, and financing choice using capital structure theories and EBIT-EPS analysis.',
        pageRange: { start: 501, end: 560 },
        tags: ['theory-heavy', 'formula-heavy', 'practice-heavy'],

        formulaSections: [
          {
            title: 'EBIT-EPS Analysis',
            description: 'Compares financing options by examining earnings per share at different EBIT levels.',
            formulas: [
              {
                name: 'EPS under Financing Plan',
                formula: 'EPS = [(EBIT - Interest)(1 - t)] / Number of Equity Shares',
                latex: 'EPS = \\frac{(EBIT - \\text{Interest})(1 - t)}{\\text{Number of Equity Shares}}',
                notation: {
                  EPS: 'Earnings per share',
                  EBIT: 'Earnings before interest and tax',
                  Interest: 'Interest on debt financing',
                  t: 'Tax rate',
                  'Number of Equity Shares': 'Total outstanding equity shares',
                },
              },
            ],
          },
        ],

        topics: [
          {
            id: 'fm-06-t1',
            title: 'Foundations of Capital Structure',
            summary: 'Introduces the meaning of capital structure and its link with cost of capital and firm value.',
            subtopics: [
              'Meaning of capital structure',
              'Relationship between capital structure and firm value',
              'Capital structure relevance vs irrelevance',
              'Levered firm vs unlevered firm',
              'Why companies use debt despite higher risk',
            ],
            pageRange: { start: 507, end: 512 },
            hasNumericals: false,
            hasExamples: true,
          },
          {
            id: 'fm-06-t2',
            title: 'Capital Structure Theories',
            summary: 'Explains the major theories that describe whether debt-equity mix affects firm value.',
            subtopics: [
              'Relevance theories:Net income approach & Traditional approach(with graph and assumptions)',
              'Irrelevance theories:Net operating income approach(with graph and assumptions)',
            ],
            pageRange: { start: 513, end: 540 },
            hasNumericals: true,
            hasExamples: true,
          },
          {
            id: 'fm-06-t3',
            title: 'EBIT-EPS Analysis',
            summary: 'Compares debt and equity financing options by analyzing their effect on earnings per share.',
            subtopics: [
              'Meaning of EBIT-EPS analysis',
              'Equity financing vs debt financing',
              'EPS calculation under different financing plans (numerical)',
              'Indifference point (numerical)',
            ],
            pageRange: { start: 552, end: 560 },
            hasNumericals: true,
            hasExamples: true,
          },
        ],
      },
      {
        id: 'fm-07',
        lessonNumber: 7,
        title: 'Capital Budgeting – Tools and Techniques',
        covers: 'Evaluates long-term investment decisions using cash flow estimation and techniques like NPV, IRR, PI, PBP, and ARR.',
        pageRange: { start: 572, end: 640 },
        tags: ['formula-heavy', 'practice-heavy'],

        formulaSections: [
          {
            title: 'Discounting Techniques',
            description: 'Time value-based methods for evaluating investment projects.',
            formulas: [
              {
                name: 'Net Present Value (NPV)',
                formula: 'NPV = Sum of Present Value of Cash Inflows − Sum of Present Value of Cash Outflows',
                latex: 'NPV = \\sum \\text{PV of Cash Inflows} - \\sum \\text{PV of Cash Outflows}',
                notation: {
                  "NPV": "Net present value",
                  "PV of Cash Inflows": "Present value of all future cash inflows",
                  "PV of Cash Outflows": "Present value of initial and other cash outflows",
                },
              },
              {
                name: 'Profitability Index (PI)',
                formula: 'PI = Sum of Present Value of Cash Inflows / Sum of Present Value of Cash Outflows',
                latex: '\\frac{\\sum \\text{PV of Cash Inflows}}{\\sum \\text{PV of Cash Outflows}}',
                notation: {
                  "PI": "Profitability index",
                  "PV of Cash Inflows": "Present value of all future cash inflows",
                  "PV of Cash Outflows": "Present value of initial investment",
                },
              },
              {
                name: 'Internal Rate of Return (IRR)',
                formula: 'IRR = L + [(P1 / (P1 − P2)) × D]',
                latex: 'IRR = L + \\left( \\frac{P_1}{P_1 - P_2} \\right) \\times D',
                notation: {
                  "IRR": "Internal rate of return",
                  "L": "Lower discount rate",
                  "P1": "NPV at lower discount rate",
                  "P2": "NPV at higher discount rate",
                  "D": "Difference between two discount rates",
                },
              },
            ],
          },
          {
            title: 'Non-Discounting Techniques',
            description: 'Simple evaluation methods based on time and accounting returns.',
            formulas: [
              {
                name: 'Payback Period (PBP)-Equal Inflows',
                formula: 'PBP = Initial Investment / Annual Cash Inflows',
                latex: 'PBP = \\frac{\\text{Initial Investment}}{\\text{Annual Cash Inflow}} \\quad',
                notation: {
                  PBP: 'Payback period',
                },
              },
              {
                name: 'Payback Period (PBP)- UnEqual Inflows',
                formula: 'PBP = Base Year + (Remaining Amount / Next Year Cash Inflow)',
                latex: 'PBP = \\text{Base Year} + \\frac{\\text{Remaining Amount}}{\\text{Next Year Cash Inflow}} ',
                notation: {
                  PBP: 'Payback period',
                  "Base Year": "Last year before full recovery of investment",
                  "Remaining Amount": "Unrecovered investment at the end of base year"
                },
              },
              {
                name: 'Accounting Rate of Return (ARR)',
                formula: 'ARR = Average Profit / Average Investment × 100',
                latex: 'ARR = \\frac{\\text{Average Profit After Tax}}{\\text{Average Investment}} \\times 100',
                notation: {
                  "ARR": "Accounting rate of return",
                  "Average Profit After Tax": "Mean annual profit after tax over the project life",
                  "Average Investment": "Average of initial and final investment"
                },
              },
            ],
          },
        ],

        topics: [
          {
            id: 'fm-07-t1',
            title: 'Introduction to Capital Budgeting',
            summary: 'Explains long-term investment decisions and their importance in financial management.',
            subtopics: [
              'Meaning of capital budgeting',
              'Nature of long-term investment decisions',
              'Importance in firm growth and value',
              'Types of capital budgeting decisions',
            ],
            pageRange: { start: 572, end: 575 },
            hasNumericals: false,
            hasExamples: true,
          },
          {
            id: 'fm-07-t2',
            title: 'Discounting Techniques',
            summary: 'Evaluates projects using time value of money-based methods.',
            subtopics: [
              'Net present value (NPV) (numerical)',
              'Decision rule for NPV',
              'Profitability index (PI) (numerical)',
              'Internal rate of return (IRR) (numerical)',
              'Comparison of NPV and IRR',
              'Conflicts between NPV and IRR',
            ],
            pageRange: { start: 590, end: 620 },
            hasNumericals: true,
            hasExamples: true,
          },
          {
            id: 'fm-07-t3',
            title: 'Non-Discounting Techniques',
            summary: 'Covers simpler methods used for quick evaluation of investment projects.',
            subtopics: [
              'Payback period (PBP) (numerical)',
              'Discounted payback period (numerical)',
              'Accounting rate of return (ARR) (numerical)',
              'Advantages and limitations of each method',
              'Comparison of all capital budgeting techniques',
            ],
            pageRange: { start: 624, end: 640 },
            hasNumericals: true,
            hasExamples: true,
          },
        ],
      },
      {
        id: 'fm-08',
        lessonNumber: 8,
        title: 'Dividend Policy & Theories',
        covers: 'Explains how firms decide dividend payouts and how dividend policy affects shareholder wealth using key theoretical models.',
        pageRange: { start: 641, end: 700 },
        tags: ['theory-heavy', 'formula-heavy'],

        formulaSections: [
          {
            title: 'Dividend Models',
            description: 'Models explaining relationship between dividends and share value.',
            formulas: [
              {
                name: 'Walter Model',
                formula: 'P = [D + (r / Ke)(E - D)] / Ke',
                latex: 'P = \\frac{D + \\left(\\frac{r}{K_e}\\right)(E - D)}{K_e}',
                notation: {
                  P: 'Market price per share',
                  D: 'Dividend per share',
                  E: 'Earnings per share',
                  r: 'Return on investment',
                  K_e: 'Cost of equity',
                },
              },
              {
                name: 'Gordon Model',
                formula: 'P = E(1 - b) / (K_e - br)',
                latex: 'P = \\frac{E(1 - b)}{K_e - b_r}',
                notation: {
                   "P": "Market price per share",
                    "E": "Earnings per share (EPS)",
                    "b": "Retention ratio (portion of earnings retained)",
                    "K_e": "Cost of equity",
                },
              },
            ],
          },
        ],

        topics: [
          {
            id: 'fm-08-t1',
            title: 'Introduction to Dividend Policy',
            summary: 'Explains the concept of dividend decisions and their role in financial management.',
            subtopics: [
              'Meaning of dividend policy',
              'Types of dividends (cash, stock, bonus)',
              'Dividend vs retained earnings decision',
              'Factors influencing dividend policy',
            ],
            pageRange: { start: 650, end: 655 },
            hasNumericals: false,
            hasExamples: true,
          },
          {
            id: 'fm-08-t2',
            title: 'Walter and Gordon model',
            summary: 'Explains theories that suggest dividend policy affects firm value.',
            subtopics: [
              'Walter model (numerical)',
              'Gordon model (numerical)',
              'Assumptions and limitations of Walter model and decision criteria',
              'Assumptions and limitations of Gordon modeland decision criteria',
              'retention ratio',
            ],
            pageRange: { start: 650, end: 680 },
            hasNumericals: true,
            hasExamples: true,
          },
        ],
      },
      {
        id: 'fm-09',
        lessonNumber: 9,
        title: 'Working Capital Management',
        covers: 'We are still working on this lesson.',
        pageRange: { start: 701, end: 760 },
        tags: ['theory-heavy', 'practice-heavy'],

        status: 'in-progress', // 👈 NEW FIELD

        formulas: [],
        topics: [],
      }
    ],//
  },
]

export function getStudySubjectById(subjectId) {
  return STUDYME_SUBJECTS.find((subject) => subject.id === subjectId) || null
}

export function getStudyLessonById(subjectId, lessonId) {
  const subject = getStudySubjectById(subjectId)
  if (!subject) {
    return null
  }

  return subject.lessons.find((lesson) => lesson.id === lessonId) || null
}
