import { precacheAndRoute } from 'workbox-precaching'
import { registerRoute } from 'workbox-routing'
import { StaleWhileRevalidate, CacheFirst } from 'workbox-strategies'
import { ExpirationPlugin } from 'workbox-expiration'

// Force the new service worker to activate immediately (don't wait for old tabs to close)
self.addEventListener('install', () => self.skipWaiting())
self.addEventListener('activate', (event) => event.waitUntil(self.clients.claim()))

// Precache all assets generated by vite-plugin-pwa
precacheAndRoute(self.__WB_MANIFEST)

// Runtime caching for Google Fonts
registerRoute(
  /^https:\/\/fonts\.googleapis\.com\/.*/i,
  new StaleWhileRevalidate({ cacheName: 'google-fonts-stylesheets' })
)
registerRoute(
  /^https:\/\/fonts\.gstatic\.com\/.*/i,
  new CacheFirst({
    cacheName: 'google-fonts-webfonts',
    plugins: [new ExpirationPlugin({ maxEntries: 10, maxAgeSeconds: 365 * 24 * 60 * 60 })],
  })
)

// ── Push Notification Handlers ──────────────────────────────────────────────

const CATEGORY_ICONS = {
  notice: '/icons/icon-192.png',
  attendance: '/icons/icon-192.png',
  timetable: '/icons/icon-192.png',
  digest: '/icons/icon-192.png',
  weekly_summary: '/icons/icon-192.png',
  nudge: '/icons/icon-192.png',
  broadcast: '/icons/icon-192.png',
}

self.addEventListener('push', (event) => {
  if (!event.data) return

  let payload
  try {
    payload = event.data.json()
  } catch {
    event.waitUntil(
      self.registration.showNotification('Attend75', {
        body: 'You have a new update — open Attend75',
        icon: '/icons/icon-192.png',
        badge: '/icons/badge-72.png',
      })
    )
    return
  }

  const {
    category = 'notice',
    title = 'Attend75',
    body = '',
    deepLink,
    priority,
    icon,
    badge,
    actions = [],
  } = payload

  const options = {
    body,
    icon: icon || CATEGORY_ICONS[category] || '/icons/icon-192.png',
    badge: badge || '/icons/badge-72.png',
    data: { deepLink, category },
    requireInteraction: priority === 'high',
    actions: actions.length > 0 ? actions : [{ action: 'open', title: 'View' }],
    tag: `attend75-${category}-${Date.now()}`,
  }

  event.waitUntil(self.registration.showNotification(title, options))
})

self.addEventListener('notificationclick', (event) => {
  event.notification.close()

  const deepLink = event.notification.data?.deepLink || '/app/dashboard'
  const urlToOpen = new URL(deepLink, self.location.origin).href

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clients) => {
      for (const client of clients) {
        if (client.url.startsWith(self.location.origin)) {
          client.focus()
          client.navigate(urlToOpen)
          return
        }
      }
      return self.clients.openWindow(urlToOpen)
    })
  )
})
