import { precacheAndRoute } from 'workbox-precaching'
import { registerRoute, NavigationRoute } from 'workbox-routing'
import { StaleWhileRevalidate, CacheFirst, NetworkFirst } from 'workbox-strategies'
import { ExpirationPlugin } from 'workbox-expiration'
import { initializeApp } from 'firebase/app'
import { getMessaging, onBackgroundMessage } from 'firebase/messaging/sw'

// Initialize Firebase in the service worker for FCM background message handling
const firebaseApp = initializeApp({
  apiKey: 'AIzaSyC1DU3v_ftnC0ZvW2cR8MQSue7ns5KxNvo',
  authDomain: 'attend75-534c2.firebaseapp.com',
  projectId: 'attend75-534c2',
  messagingSenderId: '222443696612',
  appId: '1:222443696612:web:0c969f294953e107aa17f1',
})
const messaging = getMessaging(firebaseApp)

// Handle FCM background messages (delivered via Google Play Services)
onBackgroundMessage(messaging, (payload) => {
  // FCM data messages — display notification using our standard format
  const data = payload.data || {}
  const { title, body, category, priority, deepLink, icon, badge } = data
  if (!title) return

  const vibrate = priority === 'high' ? [200, 100, 200, 100, 200] : [100, 50, 100]
  const options = {
    body: body || '',
    icon: icon || '/icons/icon-192.png',
    badge: badge || '/icons/badge-72.png',
    data: { deepLink: deepLink || '/app/dashboard', category: category || 'broadcast' },
    vibrate,
    requireInteraction: priority === 'high',
    tag: `attend75-${category || 'fcm'}-${Date.now()}`,
    renotify: true,
  }
  return self.registration.showNotification(title, options)
})

// Force the new service worker to activate immediately (don't wait for old tabs to close)
self.addEventListener('install', () => self.skipWaiting())
self.addEventListener('activate', (event) => event.waitUntil(self.clients.claim()))

// Precache all assets generated by vite-plugin-pwa
precacheAndRoute(self.__WB_MANIFEST)

// Navigation requests (HTML pages) — always try network first so app updates are immediate
registerRoute(
  new NavigationRoute(
    new NetworkFirst({
      cacheName: 'pages',
      networkTimeoutSeconds: 3,
    })
  )
)

// Runtime caching for Google Fonts
registerRoute(
  /^https:\/\/fonts\.googleapis\.com\/.*/i,
  new StaleWhileRevalidate({ cacheName: 'google-fonts-stylesheets' })
)
registerRoute(
  /^https:\/\/fonts\.gstatic\.com\/.*/i,
  new CacheFirst({
    cacheName: 'google-fonts-webfonts',
    plugins: [new ExpirationPlugin({ maxEntries: 10, maxAgeSeconds: 365 * 24 * 60 * 60 })],
  })
)

// ── Push Notification Handlers ──────────────────────────────────────────────

const CATEGORY_ICONS = {
  notice: '/icons/icon-192.png',
  attendance: '/icons/icon-192.png',
  timetable: '/icons/icon-192.png',
  digest: '/icons/icon-192.png',
  weekly_summary: '/icons/icon-192.png',
  nudge: '/icons/icon-192.png',
  broadcast: '/icons/icon-192.png',
}

self.addEventListener('push', (event) => {
  if (!event.data) return

  let payload
  try {
    payload = event.data.json()
  } catch {
    event.waitUntil(
      self.registration.showNotification('Attend75', {
        body: 'You have a new update — open Attend75',
        icon: '/icons/icon-192.png',
        badge: '/icons/badge-72.png',
        vibrate: [100, 50, 100],
      })
    )
    return
  }

  const {
    category = 'notice',
    title = 'Attend75',
    body = '',
    deepLink,
    priority,
    icon,
    badge,
    actions = [],
  } = payload

  // Category-specific action buttons
  const categoryActions = {
    notice: [{ action: 'open', title: '📄 View Notice' }],
    attendance: [{ action: 'open', title: '📊 View Dashboard' }],
    broadcast: [{ action: 'open', title: '🔔 Open App' }],
    timetable: [{ action: 'open', title: '📅 View Timetable' }],
    weekly_summary: [{ action: 'open', title: '📈 View Summary' }],
    digest: [{ action: 'open', title: '📋 View Schedule' }],
  }

  // Vibration patterns by priority
  const vibrate = priority === 'high' ? [200, 100, 200, 100, 200] : [100, 50, 100]

  const options = {
    body,
    icon: icon || CATEGORY_ICONS[category] || '/icons/icon-192.png',
    badge: badge || '/icons/badge-72.png',
    data: { deepLink: deepLink || '/app/dashboard', category },
    requireInteraction: priority === 'high',
    vibrate,
    actions: actions.length > 0 ? actions : (categoryActions[category] || [{ action: 'open', title: 'View' }]),
    tag: `attend75-${category}-${Date.now()}`,
    renotify: true,
  }

  event.waitUntil(self.registration.showNotification(title, options))
})

self.addEventListener('notificationclick', (event) => {
  event.notification.close()

  // Get deep link from notification data, action click, or default to dashboard
  const deepLink = event.notification.data?.deepLink || '/app/dashboard'
  const urlToOpen = new URL(deepLink, self.location.origin).href

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clients) => {
      // Try to find an existing app window and navigate it
      for (const client of clients) {
        if (client.url.startsWith(self.location.origin)) {
          return client.focus().then(() => {
            // Post message to navigate — more reliable than client.navigate()
            client.postMessage({ type: 'NOTIFICATION_CLICK', url: urlToOpen })
            return client
          })
        }
      }
      // No existing window — open a new one
      return self.clients.openWindow(urlToOpen)
    })
  )
})
